export const data = {
  POKEDEX: {
    image: "./pokedex-photo.png",
    title: "Pokedex Project",
    description: "Application with all the pokemons details of the pokemon universe. Responsive application developed for web consuming an external API.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "ChakraUI",
    tech_fourth: "Axios",
    tech_fifth: "Pokeapi",
    linkVisit: "https://pokedex-project-reactjs.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/pokedex_project_reactjs",
  },

  DTMONEY: {
    image: "./dtmoney-photo.png",
    title: "DT Money",
    description: "This Application was developed to manager inflow and outflow money process of you own life or business.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Styled-Components",
    tech_fourth: "React-Hook-Form",
    tech_fifth: "Axios",
    tech_sixth: "Json-server",
    linkGithub: "https://github.com/douglassantiagos/dt_money_reactjs",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  IGNEWS: {
    image: "./ignews-photo.png",
    title: "Ignews",
    description: "Ignews is a content blog with a purchase system integrated with STRIPE. Upon payment, the subscription will be active for full access to the blog. Otherwise, the user will have limited access to the contents.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Next.js",
    tech_fourth: "Prismic",
    tech_fifth: "Fauna-db",
    tech_sixth: "Stripe",
    linkVisit: "https://ignews-swart-mu.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/Ignews",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  JOBSCALC: {
    image: "./jobscalc-photo.png",
    title: "JobsCalc",
    description: "JobsCalc is a calculation website for freelance projects, which aims to register and exclude jobs (projects), obtaining a cost estimate for each job.",
    tech_pri: "Javascript",
    tech_sec: "NodeJS",
    tech_third: "EJS",
    tech_fourth: "SQLite",
    tech_fifth: "HTML/CSS",
    linkGithub: "https://github.com/douglassantiagos/Maratona-JobsCalc",
    className: "flex flex-row space-x-4 shadow-xl rounded-xl mt-20",
  },

  COFFEEDELIVERY: {
    image: "./coffee-delivery.png",
    title: "Coffee Delivery",
    description: "Coffee Delivery is an application to manage a shopping cart for a fictional coffee shop.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Styled Components",
    tech_fourth: "React-Hook-Form",
    tech_fifth: "React-Router-Dom",
    tech_sixth: "Vite",
    linkVisit: "https://coffee-delivery-project.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/coffee_delivery",
    className: "flex flex-row space-x-4 shadow-xl rounded-xl mt-20",
  },

  IGNITETIMER: {
    image: "./ignite_timer.png",
    title: "Ignite Timer",
    description: "The Ignite Timer is a pomodoro based on the idea of ​​dividing the flow of tasks into blocks of time, improving intense brain agility and stimulating focus.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Styled Components",
    tech_fourth: "React-Hook-Form",
    tech_fifth: "React-Router-Dom",
    tech_sixth: "Vite",
    linkVisit: "https://ignite-timer-project.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/ignite_timer_reactjs",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  TODOLIST: {
    image: "./todolist.png",
    title: "ToDo",
    description: "Todo is a to-do list-style task control application, which contains the following functionalities as add and remove a new task from the listing, mark and unmark a task as complete and show task completion progress.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Vite",
    tech_fourth: "HTML",
    tech_fifth: "CSS",
    linkVisit: "https://projecttodolist.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/desafio_todo_list_reactjs",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  WORLDTRIP: {
    image: "./layout-worldtrip.png",
    title: "WorldTrip",
    description: "Ignite course challenge to create a responsive landing page, with current technologies such as react and next.js. The website tells stories and their curiosities from each continent.",
    tech_pri: "Typescript",
    tech_sec: "Next.js",
    tech_third: "React",
    tech_fourth: "ChakraUI",
    tech_fifth: "Swiper",
    linkVisit: "https://worldtrip-phi-eight.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/reactjs-desafio07-interface-com-chakra-ui",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  WIDGETFEEDBACK: {
    image: "./widget-feedback.png",
    title: "Widget Feedback",
    description: "This project was developed at Next Level Week - Return Impulse event, by Rocketseat. The Application was created to send feedbacks about website developed from a widget.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Tailwindcss",
    tech_fourth: "Axios",
    tech_fifth: "Vite.js",
    linkVisit: "https://nlw-feedback-widget-web-ruby.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/nlw-feedbackWidget-web",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  }
}