export const data = {
  POKEDEX: {
    image: "./pokedex-photo.png",
    title: "Pokedex Project",
    subtitle: "Application with all the pokemons details of the pokemon universe. Responsive application developed for web consuming an external API.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "ChakraUI",
    tech_fourth: "Axios",
    tech_fifth: "Pokeapi",
    linkVisit: "https://pokedex-project-reactjs.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/pokedex_project_reactjs",
  },

  IGNEWS: {
    image: "./ignews-photo.png",
    title: "Ignews",
    subtitle: "Ignews is a content blog with a purchase system integrated with STRIPE. Upon payment, the subscription will be active for full access to the blog. Otherwise, the user will have limited access to the contents.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Next.js",
    tech_fourth: "Prismic",
    tech_fifth: "Fauna-db",
    tech_sixth: "Stripe",
    linkVisit: "https://ignews-swart-mu.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/Ignews",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  JOBSCALC: {
    image: "./jobscalc-photo.png",
    title: "JobsCalc",
    subtitle: "JobsCalc is a calculation website for freelance projects, which aims to register and exclude jobs (projects), obtaining a cost estimate for each job.",
    tech_pri: "Javascript",
    tech_sec: "NodeJS",
    tech_third: "EJS",
    tech_fourth: "Express",
    tech_fifth: "SQLite",
    tech_sixth: "HTML/CSS",
    linkGithub: "https://github.com/douglassantiagos/Maratona-JobsCalc",
    className: "flex flex-row space-x-4 shadow-xl rounded-xl mt-20",
  },

  WORLDTRIP: {
    image: "./layout-worldtrip.png",
    title: "WorldTrip",
    subtitle: "Ignite course challenge to create a responsive landing page, with current technologies such as react and next.js. The website tells stories and their curiosities from each continent.",
    tech_pri: "Typescript",
    tech_sec: "Next.js",
    tech_third: "React",
    tech_fourth: "ChakraUI",
    tech_fifth: "Swiper",
    linkVisit: "https://worldtrip-phi-eight.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/reactjs-desafio07-interface-com-chakra-ui",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  },

  WIDGETFEEDBACK: {
    image: "./widget-feedback.png",
    title: "Widget Feedback",
    subtitle: "This project was developed at Next Level Week - Return Impulse event, by Rocketseat. The Application was created to send feedbacks about website developed from a widget.",
    tech_pri: "Typescript",
    tech_sec: "React",
    tech_third: "Tailwindcss",
    tech_fourth: "Axios",
    tech_fifth: "Vite.js",
    linkVisit: "https://nlw-feedback-widget-web-ruby.vercel.app/",
    linkGithub: "https://github.com/douglassantiagos/nlw-feedbackWidget-web",
    className: "flex flex-row-reverse space-x-4 shadow-xl rounded-xl mt-20",
  }
}